### ISSUE TITLE
Progress output

### ISSUE THREAD

**Issue by cheekolegend** [Ati-74/Trackrefiner#2]
Hi Ati, I am processing some large data sets (200-400 images) with thousands of cells in each frame. The script takes a while to run (which is expected), so it would be helpful to track the progress of the data processing. Would it be possible to implement a way to provide feedback to the user what image number the algorithm is processing as it runs?

**Comment by Ati-74** [comment]
Hi Aaron, 
This issue has been resolved, thanks
